blank_issues_enabled: false
contact_links:
  - name: General Discussions & Questions
    url: https://github.com/LeulTew/Chikela/discussions
    about: For general questions, questions about the database decision, or brainstorming features.
