const en = {
  title: "Condition stock",
  description: "Inspect owned equipment that is damaged or under repair. These balances are separate from return receipts and item descriptions.",
  search: "Search condition stock",
  searchAction: "Search",
  includeArchived: "Include archived items",
  empty: "No unavailable stock or condition history matches this search.",
  loading: "Loading condition stock",
  unavailable: "Condition stock could not be loaded. No balance or history can be assumed.",
  forbidden: "Current inventory read or reconciliation permission is required.",
  identityUnavailable: "Your current account identity or permissions could not be verified. Sign in with a current account before inspecting or resolving stock.",
  signInAgain: "Sign in again",
  historicalTime: "New resolutions record UTC. Older records retain their stored clock values; their original timezone was not recorded.",
  readOnly: "Read-only inspection. Reconciliation permission is required to resolve stock.",
  archived: "Archived",
  archivedHelp: "This item is archived. History and saved outcomes remain available; new resolutions are not allowed.",
  inspect: "Inspect",
  location: "Location",
  unit: "Unit",
  itemReference: "Item reference",
  inactiveLocation: "Inactive location",
  unknownLocationStatus: "Location status not recorded",
  owned: "Owned",
  damaged: "Damaged",
  repair: "Under repair",
  good: "Good / usable",
  lost: "Lost",
  balancesHelp: "Owned stock includes damaged and repair balances. Availability also accounts for all active allocations.",
  history: "Resolution history",
  historyEmpty: "No condition resolutions are recorded in this snapshot.",
  notRecorded: "Not recorded",
  previous: "Previous",
  next: "Next",
  refresh: "Refresh reads",
  close: "Close detail",
  source: "Source condition",
  outcome: "Outcome",
  quantity: "Quantity",
  notes: "Inspection notes",
  limit: "Use a whole number from 1 to 1,000,000, no greater than the source balance.",
  resolve: "Record resolution",
  sameCondition: "Keeping the same condition records an inspection without changing balances.",
  saving: "Confirming resolution…",
  saved: "Resolution recorded",
  savedHelp: "The matching ledger record confirms this request. Read refreshes are separate and may still be pending.",
  stale: "Displayed balances or history may be stale. Refresh reads before another resolution.",
  checking: "Checking saved outcome…",
  check: "Check saved outcome",
  retry: "Retry exact request",
  recovery: "Saved request needs review",
  reviewRequest: "Review saved request",
  request: "Request identity",
  unknown: "The outcome is not confirmed. This request may already have committed. Check the saved outcome or deliberately retry the exact request; do not create a replacement.",
  noRecord: "No matching record was visible in that snapshot. An earlier in-flight request may still commit.",
  conflict: "Stock changed or the request was rejected. Refresh balances and review the quantities.",
  mismatch: "A saved record does not match this request's item, actor or intent. Nothing has been confirmed. Keep this identity and ask an administrator to investigate.",
  rejected: "The request was not accepted. Your inputs are retained.",
  missing: "This item is missing or archived. Inspect its history before deciding what to do next.",
  access: "Your account or permission changed. No new request is allowed; any earlier uncertain outcome still needs verification.",
  admission: "Current access could not be verified. Nothing new was sent; your inputs and any earlier uncertain request are retained.",
  offline: "You are offline. Nothing new was sent or queued. Reconnect, then choose an action yourself.",
  storage: "Safe recovery storage is unavailable or has changed. No unprotected write will be sent. Restore storage access and check the retained request.",
  read: "The saved outcome could not be checked. This does not establish whether an earlier request committed.",
  storageRetry: "Read recovery storage again",
  editRejected: "Edit rejected request",
  another: "Start another resolution",
  finishReview: "Finish request review",
  activeRequest: "Finish reviewing the retained request before submitting another.",
  lossTitle: "Confirm equipment loss",
  lossBody: "This removes the quantity below from owned stock and records an immutable loss movement. It cannot be undone in this workflow.",
  confirmLoss: "Confirm loss",
  keepEditing: "Keep editing",
  movements: "View stock movements",
  historyIdentity: "Resolution",
  actor: "Recorded by",
};

const am: Record<keyof typeof en, string> = {
  title: "የዕቃ ሁኔታ ክምችት",
  description: "የተበላሹ ወይም በጥገና ላይ ያሉ የባለቤትነት ዕቃዎችን ይመርምሩ። እነዚህ መጠኖች ከመመለሻ ደረሰኞችና ከዕቃ መግለጫዎች የተለዩ ናቸው።",
  search: "የዕቃ ሁኔታ ክምችት ፈልግ",
  searchAction: "ፈልግ",
  includeArchived: "በማህደር ያሉ ዕቃዎችን አካትት",
  empty: "ከዚህ ፍለጋ ጋር የሚዛመድ ያልተዘጋጀ ክምችት ወይም የሁኔታ ታሪክ የለም።",
  loading: "የዕቃ ሁኔታ ክምችት በመጫን ላይ",
  unavailable: "የዕቃ ሁኔታ ክምችት አልተጫነም። መጠኑን ወይም ታሪኩን መገመት አይቻልም።",
  forbidden: "የአሁን ክምችት የማንበብ ወይም የማመሳከር ፈቃድ ያስፈልጋል።",
  identityUnavailable: "የአሁኑን መለያዎን ወይም ፈቃድዎን ማረጋገጥ አልተቻለም። ክምችትን ከመመርመርዎ ወይም ከማስተካከልዎ በፊት በአሁኑ መለያዎ ይግቡ።",
  signInAgain: "እንደገና ይግቡ",
  historicalTime: "አዲስ ውሳኔዎች UTC ጊዜን ይመዘግባሉ። የቆዩ መዝገቦች የተቀመጠውን ጊዜ ያቆያሉ፤ የመጀመሪያው የሰዓት ክልል አልተመዘገበም።",
  readOnly: "ማየት ብቻ ይቻላል። የክምችት ሁኔታን ለመፍታት የማመሳከር ፈቃድ ያስፈልጋል።",
  archived: "በማህደር ያለ",
  archivedHelp: "ይህ ዕቃ በማህደር ውስጥ ነው። ታሪኩንና የተመዘገቡ ውጤቶችን ማየት ይቻላል፤ አዲስ የሁኔታ ውሳኔ ግን አይፈቀድም።",
  inspect: "መርምር",
  location: "ቦታ",
  unit: "መለኪያ",
  itemReference: "የዕቃ መለያ",
  inactiveLocation: "ንቁ ያልሆነ ቦታ",
  unknownLocationStatus: "የቦታው ሁኔታ አልተመዘገበም",
  owned: "በባለቤትነት ያለ",
  damaged: "የተበላሸ",
  repair: "በጥገና ላይ",
  good: "ጤናማ / ለአገልግሎት ዝግጁ",
  lost: "የጠፋ",
  balancesHelp: "የባለቤትነት ክምችት የተበላሹና በጥገና ያሉ ዕቃዎችን ያካትታል። ተደራሽነት ሁሉንም ንቁ ምደባዎች ያካትታል።",
  history: "የሁኔታ ውሳኔ ታሪክ",
  historyEmpty: "በዚህ የንባብ ጊዜ የተመዘገበ የሁኔታ ውሳኔ የለም።",
  notRecorded: "አልተመዘገበም",
  previous: "ያለፈው",
  next: "ቀጣይ",
  refresh: "ንባቦችን አድስ",
  close: "ዝርዝሩን ዝጋ",
  source: "የመነሻ ሁኔታ",
  outcome: "ውጤት",
  quantity: "ብዛት",
  notes: "የምርመራ ማስታወሻ",
  limit: "ከ1 እስከ 1,000,000 ያለ ሙሉ ቁጥር ያስገቡ፤ ከመነሻው መጠን መብለጥ የለበትም።",
  resolve: "የሁኔታ ውሳኔ መዝግብ",
  sameCondition: "ሁኔታውን ሳይቀይሩ ምርመራ መመዝገብ መጠኖቹን አይቀይርም።",
  saving: "የሁኔታ ውሳኔን በማረጋገጥ ላይ…",
  saved: "የሁኔታ ውሳኔ ተመዝግቧል",
  savedHelp: "የሚዛመደው የመዝገብ ማስረጃ ይህን ጥያቄ ያረጋግጣል። ንባቦችን ማደስ የተለየ ነው፤ ገና በሂደት ላይ ሊሆን ይችላል።",
  stale: "የሚታዩት መጠኖች ወይም ታሪክ የቆዩ ሊሆኑ ይችላሉ። ከሌላ ውሳኔ በፊት ንባቦችን ያድሱ።",
  checking: "የተመዘገበውን ውጤት በመፈተሽ ላይ…",
  check: "የተመዘገበውን ውጤት ፈትሽ",
  retry: "ያንኑ ጥያቄ እንደገና ሞክር",
  recovery: "የተቀመጠው ጥያቄ ምርመራ ይፈልጋል",
  reviewRequest: "የተቀመጠውን ጥያቄ መርምር",
  request: "የጥያቄ መለያ",
  unknown: "ውጤቱ አልተረጋገጠም። ጥያቄው ተመዝግቦ ሊሆን ይችላል። ውጤቱን ይፈትሹ ወይም በግልጽ ውሳኔ ያንኑ ጥያቄ ይድገሙ፤ ምትክ ጥያቄ አይፍጠሩ።",
  noRecord: "በዚያ የንባብ ጊዜ ተዛማጅ መዝገብ አልታየም። ቀድሞ የተላከ ጥያቄ ገና ሊመዘገብ ይችላል።",
  conflict: "ክምችቱ ተቀይሯል ወይም ጥያቄው አልተቀበለም። መጠኖቹን አድሰው ይመርምሩ።",
  mismatch: "የተመዘገበው ማስረጃ ከዚህ ጥያቄ ዕቃ፣ ተጠቃሚ ወይም ዝርዝር ጋር አይዛመድም። ምንም አልተረጋገጠም። መለያውን ያቆዩና አስተዳዳሪን ያነጋግሩ።",
  rejected: "ጥያቄው አልተቀበለም። ያስገቡት መረጃ ተጠብቋል።",
  missing: "ይህ ዕቃ አልተገኘም ወይም በማህደር ውስጥ ነው። ቀጣዩን እርምጃ ከመወሰንዎ በፊት ታሪኩን ይመርምሩ።",
  access: "መለያዎ ወይም ፈቃድዎ ተቀይሯል። አዲስ ጥያቄ አይፈቀድም፤ ቀድሞ ያልተረጋገጠ ውጤት ግን ማረጋገጥ ይፈልጋል።",
  admission: "የአሁኑን ፈቃድ ማረጋገጥ አልተቻለም። አዲስ ጥያቄ አልተላከም፤ ያስገቡት መረጃና ቀድሞ ያልተረጋገጠ ጥያቄ ተጠብቀዋል።",
  offline: "ከመስመር ውጭ ነዎት። አዲስ ጥያቄ አልተላከም ወይም ወረፋ አልያዘም። ተገናኝተው እርምጃውን ራስዎ ይምረጡ።",
  storage: "የመልሶ ማረጋገጫ ማከማቻ አይገኝም ወይም ተቀይሯል። ያልተጠበቀ ጥያቄ አይላክም። ማከማቻውን መልሰው የተቀመጠውን ጥያቄ ይፈትሹ።",
  read: "የተመዘገበውን ውጤት መፈተሽ አልተቻለም። ይህ የቀድሞው ጥያቄ መመዝገቡን ወይም አለመመዝገቡን አያረጋግጥም።",
  storageRetry: "የማረጋገጫ ማከማቻውን እንደገና አንብብ",
  editRejected: "ያልተቀበለውን ጥያቄ አርትዕ",
  another: "ሌላ የሁኔታ ውሳኔ ጀምር",
  finishReview: "የጥያቄ ምርመራውን ጨርስ",
  activeRequest: "ሌላ ጥያቄ ከማቅረብዎ በፊት የተቀመጠውን ጥያቄ ምርመራ ያጠናቅቁ።",
  lossTitle: "የዕቃ መጥፋት አረጋግጥ",
  lossBody: "ከታች ያለው ብዛት ከባለቤትነት ክምችት ይቀነሳል፤ የማይለወጥ የጥፋት መዝገብም ይፈጠራል። በዚህ የሥራ ሂደት መመለስ አይቻልም።",
  confirmLoss: "ጥፋቱን አረጋግጥ",
  keepEditing: "ማርትዕ ቀጥል",
  movements: "የክምችት እንቅስቃሴዎችን እይ",
  historyIdentity: "የሁኔታ ውሳኔ",
  actor: "የመዘገበው",
};

export type ConditionCopy = Record<keyof typeof en, string>;
export const conditionStockCopy = (language: string): ConditionCopy => language === "am" ? am : en;
